export const rosterData = [
    {
        key: 'Steven',
        name: 'Steven Vu',
        img: '/people/steven.jpg',
        status: 'Active',
        primary: '/guns/primary/stevenPrimary.png',
        sidearm: '/guns/sidearms/stevenM9.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Phi',
        name: 'Phi Vu',
        img: '/people/phi.png',
        status: 'Active',
        primary: '/guns/primary/phiPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/phiChest.png',
        accessory1: '/gear/accessories/phi1.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Justin',
        name: 'Justin Dang',
        img: '/people/justin.png',
        status: 'Active',
        primary: '/guns/primary/stevenPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'JJ',
        name: 'JJ Gaerlan',
        img: '/people/jj.png',
        status: 'MIA',
        primary: '/guns/primary/jjPrimary.png',
        sidearm: '/guns/sidearms/jjPM.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Lou',
        name: 'Lou Nguyen',
        img: '/people/lou.png',
        status: 'Deceased',
        primary: '/guns/primary/stevenPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Phat',
        name: 'Phát Trầnn',
        img: '/people/phat.png',
        status: 'Active',
        primary: '/guns/primary/jjPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Anh',
        name: 'Anh Nguyen',
        img: '/people/anh.png',
        status: 'Active',
        primary: '/guns/primary/stevenPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Ricky',
        name: 'Ricky Bờm Trần',
        img: '/people/ricky.png',
        status: 'Active',
        primary: '/guns/primary/jjPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Khoa',
        name: 'Khoa',
        img: '/people/khoa.png',
        status: 'Active',
        primary: '/guns/primary/phiPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Sandy',
        name: 'Sandy Trinh',
        img: '/people/sandy.png',
        status: 'Active',
        primary: '/guns/primary/phiPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
    {
        key: 'Jason',
        name: 'Jason Nguyen',
        img: '/people/jason.png',
        status: 'Active',
        primary: '/guns/primary/jjPrimary.png',
        sidearm: '/guns/sidearms/phiGlock.png',
        head: '/gear/headwear/phiHead.png',
        chest: '/gear/chest/stevenChest.png',
        accessory1: '/sign.png',
        accessory2: '/sign.png',
    },
];